const fs=require('fs');
const workflowPath=process.argv[2] || 'workflow/clinic-appointment-agent.json';
const wf=JSON.parse(fs.readFileSync(workflowPath,'utf8'));
const nodes=Object.fromEntries(wf.nodes.map(n=>[n.name,n]));
const codes=Object.fromEntries(wf.nodes.filter(n=>n.type==='n8n-nodes-base.code').map(n=>[n.name,n.parameters.jsCode]));
function run(name,inputItems,nodeMap={},extra={}){
  const $input={item:inputItems[0], all:()=>inputItems, first:()=>inputItems[0]};
  const dollar=(n)=>({first:()=>({json:nodeMap[n]}), item:{json:nodeMap[n]}});
  const fn=new Function('$input','$','$execution',codes[name]);
  return fn($input,dollar,extra.$execution||{id:'exec-test'});
}
function assert(cond,msg){if(!cond)throw new Error(msg)}
let pass=0,fail=0;
function t(name,fn){try{fn();console.log('PASS',name);pass++;}catch(e){console.error('FAIL',name,'-',e.message);fail++;}}

const currentPayload={json:{body:{message:{toolCallList:[{id:'tc1',name:'book_appointment',parameters:{patient_name:'Ali Khan',doctor_name:'Dr Ahmed',date:'2026-09-09',time:'18:10',language:'ur'}}],call:{customer:{number:'03001234567'}}}}}};
t('Current Vapi toolCallList parsed + caller ID normalized',()=>{const r=run('BS Extract',[currentPayload]);assert(r.json.toolCallId==='tc1','toolCallId');assert(r.json.phone==='+923001234567','phone');assert(r.json.lang==='ur','lang');assert(r.json.validInput===true,'valid')});

t('Legacy Vapi toolCalls still parsed',()=>{const p={json:{body:{message:{toolCalls:[{id:'old',function:{arguments:{patient_name:'Sara',doctor_name:'Dr Sara',date:'2026-09-09',time:'19:00',language:'en',phone:'03111234567'}}}]}}}};const r=run('BS Extract',[p]);assert(r.json.toolCallId==='old','id');assert(r.json.phone==='+923111234567','phone')});

t('Doctor search by specialization',()=>{const meta={lang:'ur',doctor_name:'',specialization:'cardiology',branch:'',gender:''};const rows=[{json:{doctor_id:'D1',doctor_name:'Dr Ahmed Ali',aliases:'Ahmed',specialization:'Cardiology',branch:'Main',status:'active',fee:'3000'}},{json:{doctor_id:'D2',doctor_name:'Dr Sara',specialization:'Dermatology',status:'active'}}];const r=run('DS Match Doctors',rows,{'DS Extract':meta})[0].json;assert(r.status==='found','status');assert(r.matches.length===1,'count');assert(r.matches[0].doctor_id==='D1','doctor')});

t('Doctor schedule open and next date found',()=>{const doctor={doctor_id:'D1',doctor_name:'Dr Ahmed',default_slot_minutes:10,off_dates:''};const q={validDate:true,date:'2026-09-09',spokenDate:'September 9',lang:'en'};const cfg={closed_days:'friday',holidays:'',minimum_notice_minutes:'15',default_slot_minutes:'10'};const rows=[{json:{doctor_id:'D1',day:'wednesday',start_time:'18:00',end_time:'19:00',slot_minutes:'10',active:'yes'}},{json:{doctor_id:'D1',day:'thursday',start_time:'18:00',end_time:'19:00',slot_minutes:'10',active:'yes'}}];const r=run('GS Schedule For Date',rows,{'GS Resolve Doctor':doctor,'GS Extract':q,'GS Get Clinic Config':cfg})[0].json;assert(r.status==='open','status '+r.status);assert(r.windows[0].slot===10,'slot');assert(r.next_available_date==='2026-09-10','next '+r.next_available_date)});

t('Clinic closed day rejected with next scheduled date',()=>{const doctor={doctor_id:'D1',doctor_name:'Dr Ahmed',default_slot_minutes:10,off_dates:''};const q={validDate:true,date:'2026-09-11',spokenDate:'September 11',lang:'en'};const cfg={closed_days:'friday',holidays:'',minimum_notice_minutes:'15',default_slot_minutes:'10'};const rows=[{json:{doctor_id:'D1',day:'saturday',start_time:'10:00',end_time:'12:00',slot_minutes:'10',active:'yes'}}];const r=run('GS Schedule For Date',rows,{'GS Resolve Doctor':doctor,'GS Extract':q,'GS Get Clinic Config':cfg})[0].json;assert(r.status==='closed','status');assert(r.next_available_date==='2026-09-12','next')});

t('Doctor one-off leave rejected',()=>{const doctor={doctor_id:'D1',doctor_name:'Dr Ahmed',default_slot_minutes:10,off_dates:'2026-09-09'};const q={validDate:true,date:'2026-09-09',spokenDate:'September 9',lang:'en'};const cfg={closed_days:'',holidays:'',minimum_notice_minutes:'15',default_slot_minutes:'10'};const rows=[{json:{doctor_id:'D1',day:'wednesday',start_time:'18:00',end_time:'19:00',slot_minutes:'10',active:'yes'}},{json:{doctor_id:'D1',day:'thursday',start_time:'18:00',end_time:'19:00',slot_minutes:'10',active:'yes'}}];const r=run('GS Schedule For Date',rows,{'GS Resolve Doctor':doctor,'GS Extract':q,'GS Get Clinic Config':cfg})[0].json;assert(r.status==='doctor_off','status');assert(r.next_available_date==='2026-09-10','next')});

t('Availability excludes busy 10-minute slot',()=>{const sched={windows:[{start:'18:00',end:'19:00',slot:10}],minimum_notice_minutes:0,next_available_date:''};const q={date:'2026-09-09',lang:'en',spokenDate:'September 9'};const doc={doctor_id:'D1',doctor_name:'Dr Ahmed'};const rows=[{json:{id:'busy',start:{dateTime:'2026-09-09T18:10:00+05:00'},end:{dateTime:'2026-09-09T18:20:00+05:00'}}}];const old=Date.now;Date.now=()=>new Date('2026-09-08T12:00:00+05:00').getTime();try{const r=run('GS Calculate Free Slots',rows,{'GS Schedule For Date':sched,'GS Extract':q,'GS Resolve Doctor':doc})[0].json;assert(r.slots.includes('18:00'),'18:00');assert(!r.slots.includes('18:10'),'busy');assert(r.slots.includes('18:20'),'18:20');}finally{Date.now=old;}});

t('Booking accepts aligned 10-minute slot',()=>{const doctor={doctor_id:'D1',doctor_name:'Dr Ahmed',default_slot_minutes:10,off_dates:''};const q={date:'2026-09-09',time:'18:10',lang:'en'};const cfg={closed_days:'',holidays:'',minimum_notice_minutes:'15',default_slot_minutes:'10'};const rows=[{json:{doctor_id:'D1',day:'wednesday',start_time:'18:00',end_time:'21:00',slot_minutes:'10',active:'yes'}}];const old=Date.now;Date.now=()=>new Date('2026-09-08T12:00:00+05:00').getTime();try{const r=run('BS Validate Schedule',rows,{'BS Resolve Doctor':doctor,'BS Extract':q,'BS Get Clinic Config':cfg})[0].json;assert(r.validSlot===true,'valid');assert(r.slot_minutes===10,'slot');}finally{Date.now=old;}});

t('Booking rejects off-grid 18:07',()=>{const doctor={doctor_id:'D1',doctor_name:'Dr Ahmed',default_slot_minutes:10,off_dates:''};const q={date:'2026-09-09',time:'18:07',lang:'en'};const cfg={closed_days:'',holidays:'',minimum_notice_minutes:'15',default_slot_minutes:'10'};const rows=[{json:{doctor_id:'D1',day:'wednesday',start_time:'18:00',end_time:'21:00',slot_minutes:'10',active:'yes'}}];const old=Date.now;Date.now=()=>new Date('2026-09-08T12:00:00+05:00').getTime();try{const r=run('BS Validate Schedule',rows,{'BS Resolve Doctor':doctor,'BS Extract':q,'BS Get Clinic Config':cfg})[0].json;assert(r.validSlot===false,'should reject');assert(r.status==='invalid_slot','status');}finally{Date.now=old;}});

t('Booking rejects slot that crosses closing time',()=>{const doctor={doctor_id:'D1',doctor_name:'Dr Ahmed',default_slot_minutes:10,off_dates:''};const q={date:'2026-09-09',time:'20:55',lang:'en'};const cfg={closed_days:'',holidays:'',minimum_notice_minutes:'15',default_slot_minutes:'10'};const rows=[{json:{doctor_id:'D1',day:'wednesday',start_time:'18:00',end_time:'21:00',slot_minutes:'10',active:'yes'}}];const old=Date.now;Date.now=()=>new Date('2026-09-08T12:00:00+05:00').getTime();try{const r=run('BS Validate Schedule',rows,{'BS Resolve Doctor':doctor,'BS Extract':q,'BS Get Clinic Config':cfg})[0].json;assert(r.validSlot===false,'should reject');}finally{Date.now=old;}});

t('Idempotent retry detected',()=>{const q={toolCallId:'same123',lang:'ur',patient_name:'Ali',phone:'+923001234567',date:'2026-09-09'};const v={startISO:'2026-09-09T18:10:00+05:00',endISO:'2026-09-09T13:20:00.000Z'};const rows=[{json:{id:'e1',description:'Phone: +923001234567\nToolCallId: same123',summary:'Appointment - Ali - Dr Ahmed',start:{dateTime:'2026-09-09T18:10:00+05:00'},end:{dateTime:'2026-09-09T18:20:00+05:00'}}}];const r=run('BS Analyze Conflict',rows,{'BS Extract':q,'BS Validate Schedule':v})[0].json;assert(r.status==='success','status');assert(r.idempotent===true,'idem')});

t('Duplicate same patient/day/doctor detected',()=>{const q={toolCallId:'new',lang:'en',patient_name:'Ali Khan',phone:'+923001234567',date:'2026-09-09'};const v={startISO:'2026-09-09T18:30:00+05:00',endISO:'2026-09-09T13:40:00.000Z'};const rows=[{json:{id:'e1',description:'Phone: +923001234567\nToolCallId: old',summary:'Appointment - Ali Khan - Dr Ahmed',start:{dateTime:'2026-09-09T18:10:00+05:00'},end:{dateTime:'2026-09-09T18:20:00+05:00'}}}];const r=run('BS Analyze Conflict',rows,{'BS Extract':q,'BS Validate Schedule':v})[0].json;assert(r.status==='already_booked','status '+r.status);assert(r.existing_appointment.time==='18:10','time')});

t('Real overlap detected',()=>{const q={toolCallId:'new',lang:'en',patient_name:'Sara',phone:'+923111111111',date:'2026-09-09'};const v={startISO:'2026-09-09T18:10:00+05:00',endISO:'2026-09-09T13:20:00.000Z'};const rows=[{json:{id:'e1',description:'Phone: +923000000000',summary:'Busy',start:{dateTime:'2026-09-09T18:10:00+05:00'},end:{dateTime:'2026-09-09T18:20:00+05:00'}}}];const r=run('BS Analyze Conflict',rows,{'BS Extract':q,'BS Validate Schedule':v})[0].json;assert(r.status==='slot_taken','status')});

t('Vapi normalize returns one-line JSON string',()=>{const x={status:'open',doctor_name:'Dr Ahmed',date:'2026-09-09',slots:['18:00','18:10'],totalFree:2,result:'Earliest is 6 PM'};const r=run('GS Normalize',[{json:x}])[0].json.vapiResult;assert(typeof r==='string','string');assert(!r.includes('\n'),'newline');const o=JSON.parse(r);assert(o.status==='open','status');assert(o.available_slots.length===2,'slots')});

t('Workflow graph connections point to existing nodes',()=>{const names=new Set(wf.nodes.map(n=>n.name));for(const [src,c] of Object.entries(wf.connections)){assert(names.has(src),'missing src '+src);for(const b of c.main||[])for(const x of b)assert(names.has(x.node),`missing dst ${x.node}`)}});

t('Webhook paths are unique',()=>{const ps=wf.nodes.filter(n=>n.type==='n8n-nodes-base.webhook').map(n=>n.parameters.path);assert(new Set(ps).size===ps.length,'duplicate paths')});

t('All Vapi Respond nodes return HTTP 200 object envelope',()=>{for(const n of wf.nodes.filter(n=>n.type==='n8n-nodes-base.respondToWebhook')){assert(n.parameters.respondWith==='json',n.name);assert(String(n.parameters.responseBody).startsWith('={{ { results:'),n.name+' response body');assert(n.parameters.options.responseCode===200,n.name+' code')}});

console.log(`TOTAL PASS ${pass} / FAIL ${fail}`);if(fail)process.exit(1);
